language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies
install: 
- pip install -U pytest
- pip install python-coveralls

# command to run tests
script: py.test

after_success:
  - coveralls
